"""empty message

Revision ID: 671f7656fa5f
Revises: a8151f7163c3
Create Date: 2025-06-10 16:13:33.886643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671f7656fa5f'
down_revision = 'a8151f7163c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
